//! Argon2id proof of work.
//!
//! The client-side counterpart of `registry/src/pow.ts`; docs/spec/PROOF-OF-WORK.md is
//! authoritative. Two properties carry the whole construction, and both are properties of what
//! is NOT in the record:
//!
//! 1. **The cost parameters are protocol constants, not record fields.** A record carrying its
//!    own `m`, `t` and `p` would let the registrant choose them, and `m = 64` KiB reduces a
//!    memory-hard function to a cheap one. The verifier would still evaluate whatever the
//!    attacker specified.
//!
//! 2. **The salt is derived from the record, not carried by it.** A carried salt is a free
//!    parameter, and a free parameter breaks the binding this construction exists to create:
//!    grind one (salt, nonce) pair to any difficulty, then attach that single proof to every
//!    record you ever sign. One proof of work would buy unlimited names.
//!
//! Deriving the salt from the record's own canonical bytes means a proof is valid for exactly
//! one record. Change the name, the owner, the term, the sequence number or the predecessor
//! hash, and the salt changes, so the tag changes, so the work must be redone.
//!
//! Every derivation this module performs is pinned against `conformance/vectors.json`, the
//! artifact generated by the registry implementation — the file a second implementation runs,
//! which is exactly how this half of the client proves it computes the same schedule.

use argon2::{Algorithm, Argon2, Params, Version};
use sha2::{Digest, Sha256};

use crate::cbor::{self, Key, Value};

/// The algorithm identifier names the parameters it was produced under.
///
/// A single opaque string rather than separate fields precisely so the parameters cannot be
/// varied per record. A future VWIP that changes the cost changes this identifier, making
/// proofs from the two regimes distinguishable rather than silently comparable.
pub const POW_ALGORITHM: &str = "argon2id-v19-m65536-t2-p1";

/// RFC 9106 Argon2id, version 0x13. Memory in KiB.
pub const POW_MEMORY_KIB: u32 = 65_536;
pub const POW_ITERATIONS: u32 = 2;
pub const POW_LANES: u32 = 1;
pub const POW_VERSION: u32 = 0x13;
pub const POW_TAG_LENGTH: usize = 32;

/// The nonce searched by the registrant.
pub const POW_NONCE_LENGTH: usize = 16;

/// Salt derivation is domain-separated from every other hash in the protocol.
const POW_SALT_PREFIX: &str = "vayuweb-pow-v1";
pub const POW_SALT_LENGTH: usize = 16;

/// Difficulty is capped so a land rush cannot make a TLD permanently unusable.
pub const MAX_DIFFICULTY_BITS: u32 = 20;

/// Difficulty epochs are one hour, so peers with skewed clocks agree on the window.
pub const EPOCH_SECONDS: u64 = 3_600;
pub const RATE_WINDOW_SECONDS: u64 = 2_592_000;

/// Registrations in the trailing window below which the rate term contributes nothing.
pub const RATE_FLOOR: u64 = 512;

fn floor_log2(value: u64) -> u32 {
    debug_assert!(value > 0);
    63 - value.leading_zeros()
}

/// Base difficulty by label length. Short labels are the ones worth hoarding, so a
/// two-character name costs 64 times a sixteen-character one: 10 bits against 4, the widest
/// spread this table produces.
pub fn base_bits(label_length: usize) -> u32 {
    if label_length <= 2 {
        return 10;
    }
    if label_length == 3 {
        return 9;
    }
    if label_length == 4 {
        return 8;
    }
    if label_length <= 6 {
        return 7;
    }
    if label_length <= 9 {
        return 6;
    }
    if label_length <= 15 {
        return 5;
    }
    4
}

/// Required difficulty for a label, given how many registrations and renewals the TLD accepted
/// in the trailing 30 days.
///
/// `window_count` is supplied by the caller rather than read here: it is index state, and this
/// function must stay a pure function of its arguments so every peer computes the same answer.
///
/// The rate term uses integer arithmetic — `floor_log2(window_count / 512)` over integers —
/// rather than floating point. For positive integers `floor(log2(a/b))` equals
/// `floor_log2(floor(a/b))`, so this matches the specification's arithmetic without exposing
/// the search to a platform's `log2` rounding at exact powers of two.
pub fn required_bits(label_length: usize, window_count: u64) -> u32 {
    let base = base_bits(label_length);
    let rate = if window_count < RATE_FLOOR {
        0
    } else {
        floor_log2(window_count / RATE_FLOOR).min(8)
    };
    (base + rate).min(MAX_DIFFICULTY_BITS)
}

/// The half-open trailing window `[start, end)` whose registrations feed the rate term.
///
/// Anchored to the epoch boundary rather than to `not_before` itself: peers whose clocks
/// disagree within an hour still derive the same window, which is the point of the epoch.
pub fn rate_window(not_before: u64) -> (u64, u64) {
    let epoch = not_before / EPOCH_SECONDS;
    let end = epoch * EPOCH_SECONDS;
    (end - RATE_WINDOW_SECONDS, end)
}

/// The salt preimage: the record without `sig` and without `powProof.nonce`.
///
/// `powProof.bits` stays in the preimage deliberately. The claimed difficulty is therefore
/// bound into the salt, so a proof produced for a low difficulty cannot be relabelled as
/// satisfying a higher one, nor the reverse.
pub fn pow_salt_preimage(record: &[(Key, Value)]) -> Result<Vec<u8>, cbor::CborError> {
    let mut stripped: Vec<(Key, Value)> = Vec::with_capacity(record.len());
    for (key, value) in record {
        let Key::Text(name) = key else {
            return Err(cbor::CborError::BadMapKey);
        };
        if name == "sig" {
            continue;
        }
        if name == "powProof" {
            let Value::Map(proof) = value else {
                return Err(cbor::CborError::BadMapKey);
            };
            let mut without_nonce = Vec::with_capacity(proof.len());
            for (proof_key, proof_value) in proof {
                let Key::Text(proof_name) = proof_key else {
                    return Err(cbor::CborError::BadMapKey);
                };
                if proof_name == "nonce" {
                    continue;
                }
                without_nonce.push((proof_key.clone(), proof_value.clone()));
            }
            stripped.push((key.clone(), Value::Map(without_nonce)));
            continue;
        }
        stripped.push((key.clone(), value.clone()));
    }
    let body = cbor::encode(&Value::Map(stripped))?;
    let mut out = Vec::with_capacity(POW_SALT_PREFIX.len() + body.len());
    out.extend_from_slice(POW_SALT_PREFIX.as_bytes());
    out.extend_from_slice(&body);
    Ok(out)
}

/// `salt = SHA-256(preimage)[0..16]`.
pub fn pow_salt(record: &[(Key, Value)]) -> Result<[u8; POW_SALT_LENGTH], cbor::CborError> {
    let hash = Sha256::digest(pow_salt_preimage(record)?);
    let mut out = [0u8; POW_SALT_LENGTH];
    out.copy_from_slice(&hash[..POW_SALT_LENGTH]);
    Ok(out)
}

/// One Argon2id evaluation at the protocol's fixed parameters.
///
/// The nonce is the password and the derived value is the salt: the registrant searches the
/// nonce space, and everything else about the evaluation is pinned by the constants above.
pub fn pow_tag(nonce: &[u8], salt: &[u8]) -> [u8; POW_TAG_LENGTH] {
    let params = Params::new(
        POW_MEMORY_KIB,
        POW_ITERATIONS,
        POW_LANES,
        Some(POW_TAG_LENGTH),
    )
    .expect("the protocol parameters are valid Params");
    let context = Argon2::new(Algorithm::Argon2id, Version::V0x13, params);
    let mut out = [0u8; POW_TAG_LENGTH];
    context
        .hash_password_into(nonce, salt, &mut out)
        .expect("hashing into a correctly sized buffer");
    out
}

/// Leading-zero-bit test over the whole tag, most-significant bit first, **no early exit**.
///
/// PROOF-OF-WORK.md makes the absence of an early exit normative. The tag is not secret, so
/// this is hygiene rather than a defence against a concrete attack — but a uniform test costs
/// nothing, and a loop that returns as soon as it sees a one bit leaks how close a rejected
/// candidate came.
pub fn tag_satisfies(tag: &[u8], bits: u32) -> bool {
    let mut leading = 0u32;
    let mut still_zero = 1u32;
    for &byte in tag.iter() {
        for shift in (0..8).rev() {
            let is_zero = u32::from((byte >> shift) & 1 == 0);
            still_zero &= is_zero;
            leading += still_zero;
        }
    }
    leading >= bits
}

/// Big-endian increment, so a search walks the nonce space without repeating.
fn increment_nonce(nonce: &mut [u8; POW_NONCE_LENGTH]) {
    for byte in nonce.iter_mut().rev() {
        let (next, overflow) = byte.overflowing_add(1);
        *byte = next;
        if !overflow {
            return;
        }
    }
}

/// Why a search found nothing.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SolveError {
    /// Canonical encoding of the skeleton failed — a caller bug, not a search outcome.
    Encode(cbor::CborError),
    /// Salt derivation failed for the same reason.
    Salt(cbor::CborError),
    /// The search exhausted `limit` evaluations without success.
    Exhausted,
}

impl core::fmt::Display for SolveError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Encode(error) => write!(f, "encoding failed during solve: {error}"),
            Self::Salt(error) => write!(f, "salt derivation failed: {error}"),
            Self::Exhausted => write!(f, "no nonce satisfied the difficulty within the limit"),
        }
    }
}

impl std::error::Error for SolveError {}

/// Search for a nonce satisfying `bits`. Used by the registrant, never by the verifier.
///
/// The expected number of evaluations is 2^bits and the distribution is geometric, so an
/// unlucky registrant pays several times the mean. The search starts from the all-zero nonce
/// and increments big-endian — a DETERMINISTIC walk, which makes solves reproducible and lets
/// golden fixtures be regenerated byte-for-byte. Production callers wanting unpredictability
/// across records already have it: the salt changes with every record.
///
/// The salt is computed once before the loop because it cannot depend on the nonce: the
/// preimage strips `powProof.nonce` by construction.
pub fn solve(
    record: &[(Key, Value)],
    bits: u32,
    limit: u64,
) -> Result<[u8; POW_NONCE_LENGTH], SolveError> {
    let salt = pow_salt(record).map_err(SolveError::Salt)?;
    let mut nonce = [0u8; POW_NONCE_LENGTH];
    for _ in 0..limit {
        increment_nonce(&mut nonce);
        let tag = pow_tag(&nonce, &salt);
        if tag_satisfies(&tag, bits) {
            return Ok(nonce);
        }
    }
    Err(SolveError::Exhausted)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn vectors() -> serde_json::Value {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../conformance/vectors.json");
        let text = std::fs::read_to_string(path).expect("conformance/vectors.json is readable");
        serde_json::from_str(&text).expect("vectors.json parses")
    }

    fn unhex(input: &str) -> Vec<u8> {
        (0..input.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&input[i..i + 2], 16).expect("valid hex"))
            .collect()
    }

    fn hex(bytes: &[u8]) -> String {
        bytes.iter().map(|b| format!("{b:02x}")).collect()
    }

    #[test]
    fn base_and_required_derivations_match_every_published_vector() {
        let data = vectors();
        let mut checked = 0;
        for vector in data["pow"].as_array().expect("pow suite") {
            let check = vector["check"].as_str().expect("check kind");
            match check {
                "baseBits" => {
                    let label_length = vector["labelLength"].as_u64().expect("label") as usize;
                    let expect = vector["expect"].as_u64().expect("bits value") as u32;
                    assert_eq!(base_bits(label_length), expect, "{}", vector["name"]);
                    checked += 1;
                }
                "requiredBits" => {
                    let label_length = vector["labelLength"].as_u64().expect("label") as usize;
                    let window_count = vector["windowCount"].as_u64().expect("count");
                    let expect = vector["expect"].as_u64().expect("bits value") as u32;
                    assert_eq!(
                        required_bits(label_length, window_count),
                        expect,
                        "{}",
                        vector["name"]
                    );
                    checked += 1;
                }
                "rateWindow" => {
                    let not_before = vector["notBefore"].as_u64().expect("instant");
                    let (start, end) = rate_window(not_before);
                    assert_eq!(
                        start,
                        vector["expect"]["start"].as_u64().expect("start"),
                        "{}",
                        vector["name"]
                    );
                    assert_eq!(
                        end,
                        vector["expect"]["end"].as_u64().expect("end"),
                        "{}",
                        vector["name"]
                    );
                    checked += 1;
                }
                _ => {} // salt and tagSatisfies have their own tests below
            }
        }
        // The suite must actually have been walked: 29 of the published vectors pin these
        // three derivations. If the artifact grows, this count is updated BY the failure,
        // which is how a silent skip is prevented.
        assert_eq!(checked, 33, "derivation vectors consumed");
    }

    #[test]
    fn the_salt_vector_pins_the_preimage_construction() {
        let data = vectors();
        let mut seen = false;
        for vector in data["pow"].as_array().expect("pow suite") {
            if vector["check"].as_str() != Some("salt") {
                continue;
            }
            seen = true;
            let record_hex = vector["record"].as_str().expect("record hex");
            let value = cbor::decode(&unhex(record_hex)).expect("vector decodes");
            let Value::Map(entries) = value else {
                panic!("vector record is a map");
            };
            let salt = pow_salt(&entries).expect("derives");
            assert_eq!(
                hex(&salt),
                vector["expect"].as_str().expect("expected salt"),
                "{}",
                vector["name"]
            );
        }
        assert!(seen, "the salt vector was present");
    }

    #[test]
    fn tag_satisfaction_matches_every_boundary_vector() {
        let data = vectors();
        let mut seen = 0;
        for vector in data["pow"].as_array().expect("pow suite") {
            if vector["check"].as_str() != Some("tagSatisfies") {
                continue;
            }
            seen += 1;
            let tag = unhex(vector["tag"].as_str().expect("tag"));
            let bits = vector["bits"].as_u64().expect("bits") as u32;
            assert_eq!(
                tag_satisfies(&tag, bits),
                vector["expect"].as_bool().expect("verdict"),
                "{}",
                vector["name"]
            );
        }
        assert_eq!(seen, 6, "boundary vectors");
    }

    #[test]
    fn counting_leading_zeros_has_no_early_exit_and_exact_boundaries() {
        // All-zero tag satisfies any bits up to the tag width.
        assert!(tag_satisfies(&[0u8; 32], 256));
        assert!(!tag_satisfies(&[0u8; 32], 257));
        // A single high bit satisfies nothing above zero bits.
        assert!(tag_satisfies(&[0xffu8; 32], 0));
        assert!(!tag_satisfies(&[0xffu8; 32], 1));
        // Seven zero bits in the first byte: satisfies 7, not 8, regardless of the rest.
        let seven = [0x01u8, 0xff, 0x00];
        assert!(tag_satisfies(&seven, 7));
        assert!(!tag_satisfies(&seven, 8));
    }

    #[test]
    fn solving_finds_a_deterministic_nonce_that_verifies() {
        // A 16-character label puts base difficulty at the 4-bit floor, so this search costs
        // ~16 evaluations of real Argon2id — a few seconds native, affordable here because the
        // determinism of the walk is itself part of what the fixture regeneration relies on.
        let label = "a".repeat(16);
        let record = vec![
            (Key::Text("op".into()), Value::Text("REGISTER".into())),
            (Key::Text("name".into()), Value::Text(label)),
        ];
        let first = solve(&record, 4, 10_000).expect("solves");
        let second = solve(&record, 4, 10_000).expect("solves");
        assert_eq!(first, second, "the walk is deterministic");
        let salt = pow_salt(&record).expect("salt");
        assert!(tag_satisfies(&pow_tag(&first, &salt), 4));
    }

    #[test]
    fn an_impossible_search_reports_exhaustion_rather_than_hanging() {
        let record = vec![(Key::Text("name".into()), Value::Text("exhaustion".into()))];
        assert_eq!(solve(&record, 30, 2), Err(SolveError::Exhausted));
    }
}
