//! The registry's vectors, run against THIS implementation.
//!
//! `conformance/vectors.json` is generated by the reference implementation
//! (`registry/src/vectors.ts`) and consumed there by its own tests. This file is the
//! mirror image of `clientbuilt.test.ts`: records authored THERE, decided HERE. If the
//! two languages ever disagree about what a record resolves to, one of these suites
//! goes red — the fork cannot ship silently.
//!
//! The resolution section is executed as a faithful port of RESOLUTION.md steps 1-10 as
//! the reference's `resolveName` implements them: host parsing, TLD ratification, label
//! rules, the visited set, head availability, lookup, the validity window, entry
//! selection by source order (`ipns`, `cid`, `alias`, first-of-type), and alias hops
//! under a budget of three per original request.

use serde_json::Value;

const VECTORS_PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../conformance/vectors.json");

fn hex_to_bytes(text: &str) -> Vec<u8> {
    (0..text.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&text[i..i + 2], 16).expect("vector hex"))
        .collect()
}

fn bytes_to_hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// One resolution decision, mirroring `resolveName`'s error names exactly.
enum Outcome {
    Ok {
        source: &'static str,
        value_hex: Option<String>,
    },
    Error(&'static str),
}

struct Record {
    bytes: Vec<u8>,
}

impl Record {
    fn not_after(&self) -> u64 {
        field_u64(&self.bytes, "notAfter").expect("notAfter")
    }
    fn op_text(&self) -> String {
        vayuweb_client::verify::peek(&self.bytes).expect("peeks").op
    }
}

fn field_u64(bytes: &[u8], name: &str) -> Result<u64, String> {
    let value = vayuweb_client::record::decode_record(bytes).map_err(|e| e.to_string())?;
    let vayuweb_client::cbor::Value::Map(members) = value else {
        return Err("a record is a CBOR map".to_string());
    };
    members
        .iter()
        .find_map(|(k, v)| match k {
            vayuweb_client::cbor::Key::Text(text) if text == name => match v {
                vayuweb_client::cbor::Value::UInt(n) => Some(*n),
                _ => None,
            },
            _ => None,
        })
        .ok_or_else(|| format!("no {name}"))
}

/// Steps 1-10 against a local index of signed records. `lookup(key)` returns the
/// record the index holds for `label.tld`, or None.
fn resolve_name(
    host: &str,
    lookup: &dyn Fn(&str) -> Option<Record>,
    has_verified_head: bool,
    now: u64,
) -> Outcome {
    let mut seen: Vec<String> = Vec::new();
    let mut current = host.to_string();
    for _hop in 0..=3usize {
        // Step 1: parse.
        let parts: Vec<&str> = current.split('.').collect();
        if parts.len() != 2 || parts[0].is_empty() || parts[1].is_empty() {
            return Outcome::Error("LABEL_INVALID");
        }
        let (label, tld) = (parts[0], parts[1]);

        // Steps 2 and 3: only a ratified extension resolves.
        if !vayuweb_client::names::is_ratified_tld(tld) {
            return Outcome::Error("TLD_UNKNOWN");
        }

        // Step 4: label rules before any lookup.
        if vayuweb_client::names::label_rejection(label).is_some() {
            return Outcome::Error("LABEL_INVALID");
        }

        // A cycle among well-formed names is named by the names in it.
        let key = format!("{label}.{tld}");
        if seen.contains(&key) {
            return Outcome::Error("ALIAS_LOOP");
        }
        seen.push(key);

        // Steps 6 and 7: availability, then the index.
        if !has_verified_head {
            return Outcome::Error("REGISTRY_UNAVAILABLE");
        }
        let Some(record) = lookup(&format!("{label}.{tld}")) else {
            return Outcome::Error("NAME_NOT_FOUND");
        };

        // Step 8: validity window and revocation, mapped to the same names. Only the
        // op, the expiry and the revoked flag move this state machine; the rest of
        // PrevView is chain-discipline input the window never reads.
        let state = vayuweb_client::verify::lifecycle_state(
            &vayuweb_client::verify::PrevView {
                op_text: record.op_text(),
                seq: 0,
                not_before: 0,
                not_after: record.not_after(),
                owner_key: [0u8; 32],
                signer_key: [0u8; 32],
                suite: 1,
                hash: [0u8; 32],
                revoked: false,
            },
            now,
        );
        match state.split(' ').next().unwrap_or(state) {
            "REVOKED" => return Outcome::Error("NAME_REVOKED"),
            "QUARANTINE" => return Outcome::Error("NAME_QUARANTINED"),
            "GRACE" => return Outcome::Error("NAME_EXPIRED"),
            "FREE" => return Outcome::Error("NAME_NOT_FOUND"),
            "LIVE" => {}
            other => panic!("unmapped lifecycle state {other:?}"),
        }

        // Step 9: select by source order; first of the selected type wins.
        let selected = vayuweb_client::view::selected_pointer(&record.bytes);
        // Step 10: an alias restarts the algorithm on the target.
        match selected {
            None => return Outcome::Error("NO_USABLE_RECORD"),
            Some(vayuweb_client::view::Selected::Ipns(_)) => {
                return Outcome::Ok {
                    source: "ipns",
                    value_hex: None,
                }
            }
            Some(vayuweb_client::view::Selected::Cid(bytes)) => {
                return Outcome::Ok {
                    source: "cid",
                    value_hex: Some(bytes_to_hex(&bytes)),
                }
            }
            Some(vayuweb_client::view::Selected::Alias(target)) => {
                current = format!("{}.{}", target.label, target.tld);
            }
        }
    }
    Outcome::Error("ALIAS_LOOP")
}

#[test]
fn every_resolution_vector_decides_as_the_reference_does() {
    let raw = std::fs::read_to_string(VECTORS_PATH).expect("vectors.json exists");
    let doc: Value = serde_json::from_str(&raw).expect("vectors.json parses");
    let vectors = doc
        .get("resolution")
        .and_then(Value::as_array)
        .expect("a resolution section")
        .clone();

    let mut failures: Vec<String> = Vec::new();
    for vector in &vectors {
        let name = vector.get("name").and_then(Value::as_str).unwrap_or("?");
        let host = vector.get("host").and_then(Value::as_str).unwrap_or("?");
        let now = vector.get("now").and_then(Value::as_u64).unwrap_or(0);
        let has_head = vector
            .get("hasVerifiedHead")
            .and_then(Value::as_bool)
            .unwrap_or(false);
        let primary = vector.get("record").and_then(Value::as_str);
        let others = vector.get("others");

        let index = |key: &str| -> Option<Record> {
            if key == host {
                return primary.map(|hex| Record {
                    bytes: hex_to_bytes(hex),
                });
            }
            others
                .and_then(Value::as_object)
                .and_then(|map| map.get(key))
                .and_then(Value::as_str)
                .map(|hex| Record {
                    bytes: hex_to_bytes(hex),
                })
        };

        let actual = match resolve_name(host, &index, has_head, now) {
            Outcome::Ok { source, value_hex } => {
                // The VALUE is compared where the vector names one, exactly as the
                // reference suite does: type alone once let two conforming readers
                // fetch different content from the same signed record.
                let names_value = vector
                    .get("expect")
                    .and_then(|e| e.get("value"))
                    .and_then(Value::as_str)
                    .is_some();
                if names_value {
                    format!("ok:{source}:{}", value_hex.unwrap_or_default())
                } else {
                    format!("ok:{source}")
                }
            }
            Outcome::Error(code) => format!("error:{code}"),
        };

        let want = match vector.get("expect") {
            Some(e) if e.get("outcome").and_then(Value::as_str) == Some("ok") => {
                let source = e.get("source").and_then(Value::as_str).unwrap_or("?");
                match e.get("value").and_then(Value::as_str) {
                    Some(value) => format!("ok:{source}:{value}"),
                    None => format!("ok:{source}"),
                }
            }
            Some(e) => format!(
                "error:{}",
                e.get("code").and_then(Value::as_str).unwrap_or("?")
            ),
            None => "?".to_string(),
        };
        if actual != want {
            failures.push(format!("{name}\n  want: {want}\n  got:  {actual}"));
        }
    }
    assert!(
        failures.is_empty(),
        "{} resolution vector(s) disagree:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
