//! The registry's vectors, run against THIS implementation.
//!
//! `conformance/vectors.json` is generated by the reference implementation
//! (`registry/src/vectors.ts`) and consumed there by its own tests. This file is the
//! mirror image of `clientbuilt.test.ts`: records authored THERE, decided HERE. If the
//! two languages ever disagree about what a record resolves to, one of these suites
//! goes red — the fork cannot ship silently.
//!
//! The resolution section is executed as a faithful port of RESOLUTION.md steps 1-10 as
//! the reference's `resolveName` implements them: host parsing, TLD ratification, label
//! rules, the visited set, head availability, lookup, the validity window, entry
//! selection by source order (`ipns`, `cid`, `alias`, first-of-type), and alias hops
//! under a budget of three per original request.

use serde_json::Value;

const VECTORS_PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../conformance/vectors.json");

fn hex_to_bytes(text: &str) -> Vec<u8> {
    (0..text.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&text[i..i + 2], 16).expect("vector hex"))
        .collect()
}

fn bytes_to_hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// One resolution decision, mirroring `resolveName`'s error names exactly.
enum Outcome {
    Ok {
        source: &'static str,
        value_hex: Option<String>,
    },
    Error(&'static str),
}

struct Record {
    bytes: Vec<u8>,
}

impl Record {
    fn not_after(&self) -> u64 {
        field_u64(&self.bytes, "notAfter").expect("notAfter")
    }
    fn op_text(&self) -> String {
        vayuweb_client::verify::peek(&self.bytes).expect("peeks").op
    }
}

fn field_u64(bytes: &[u8], name: &str) -> Result<u64, String> {
    let value = vayuweb_client::record::decode_record(bytes).map_err(|e| e.to_string())?;
    let vayuweb_client::cbor::Value::Map(members) = value else {
        return Err("a record is a CBOR map".to_string());
    };
    members
        .iter()
        .find_map(|(k, v)| match k {
            vayuweb_client::cbor::Key::Text(text) if text == name => match v {
                vayuweb_client::cbor::Value::UInt(n) => Some(*n),
                _ => None,
            },
            _ => None,
        })
        .ok_or_else(|| format!("no {name}"))
}

/// Steps 1-10 against a local index of signed records. `lookup(key)` returns the
/// record the index holds for `label.tld`, or None.
fn resolve_name(
    host: &str,
    lookup: &dyn Fn(&str) -> Option<Record>,
    has_verified_head: bool,
    now: u64,
) -> Outcome {
    let mut seen: Vec<String> = Vec::new();
    let mut current = host.to_string();
    for _hop in 0..=3usize {
        // Step 1: parse.
        let parts: Vec<&str> = current.split('.').collect();
        if parts.len() != 2 || parts[0].is_empty() || parts[1].is_empty() {
            return Outcome::Error("LABEL_INVALID");
        }
        let (label, tld) = (parts[0], parts[1]);

        // Steps 2 and 3: only a ratified extension resolves.
        if !vayuweb_client::names::is_ratified_tld(tld) {
            return Outcome::Error("TLD_UNKNOWN");
        }

        // Step 4: label rules before any lookup.
        if vayuweb_client::names::label_rejection(label).is_some() {
            return Outcome::Error("LABEL_INVALID");
        }

        // A cycle among well-formed names is named by the names in it.
        let key = format!("{label}.{tld}");
        if seen.contains(&key) {
            return Outcome::Error("ALIAS_LOOP");
        }
        seen.push(key);

        // Steps 6 and 7: availability, then the index.
        if !has_verified_head {
            return Outcome::Error("REGISTRY_UNAVAILABLE");
        }
        let Some(record) = lookup(&format!("{label}.{tld}")) else {
            return Outcome::Error("NAME_NOT_FOUND");
        };

        // Step 8: validity window and revocation, mapped to the same names. Only the
        // op, the expiry and the revoked flag move this state machine; the rest of
        // PrevView is chain-discipline input the window never reads.
        let state = vayuweb_client::verify::lifecycle_state(
            &vayuweb_client::verify::PrevView {
                op_text: record.op_text(),
                seq: 0,
                not_before: 0,
                not_after: record.not_after(),
                owner_key: [0u8; 32],
                signer_key: [0u8; 32],
                suite: 1,
                hash: [0u8; 32],
                revoked: false,
            },
            now,
        );
        match state.split(' ').next().unwrap_or(state) {
            "REVOKED" => return Outcome::Error("NAME_REVOKED"),
            "QUARANTINE" => return Outcome::Error("NAME_QUARANTINED"),
            "GRACE" => return Outcome::Error("NAME_EXPIRED"),
            "FREE" => return Outcome::Error("NAME_NOT_FOUND"),
            "LIVE" => {}
            other => panic!("unmapped lifecycle state {other:?}"),
        }

        // Step 9: select by source order; first of the selected type wins.
        let selected = vayuweb_client::view::selected_pointer(&record.bytes);
        // Step 10: an alias restarts the algorithm on the target.
        match selected {
            None => return Outcome::Error("NO_USABLE_RECORD"),
            Some(vayuweb_client::view::Selected::Ipns(_)) => {
                return Outcome::Ok {
                    source: "ipns",
                    value_hex: None,
                }
            }
            Some(vayuweb_client::view::Selected::Cid(bytes)) => {
                return Outcome::Ok {
                    source: "cid",
                    value_hex: Some(bytes_to_hex(&bytes)),
                }
            }
            Some(vayuweb_client::view::Selected::Alias(target)) => {
                current = format!("{}.{}", target.label, target.tld);
            }
        }
    }
    Outcome::Error("ALIAS_LOOP")
}

#[test]
fn every_resolution_vector_decides_as_the_reference_does() {
    let raw = std::fs::read_to_string(VECTORS_PATH).expect("vectors.json exists");
    let doc: Value = serde_json::from_str(&raw).expect("vectors.json parses");
    let vectors = doc
        .get("resolution")
        .and_then(Value::as_array)
        .expect("a resolution section")
        .clone();

    let mut failures: Vec<String> = Vec::new();
    for vector in &vectors {
        let name = vector.get("name").and_then(Value::as_str).unwrap_or("?");
        let host = vector.get("host").and_then(Value::as_str).unwrap_or("?");
        let now = vector.get("now").and_then(Value::as_u64).unwrap_or(0);
        let has_head = vector
            .get("hasVerifiedHead")
            .and_then(Value::as_bool)
            .unwrap_or(false);
        let primary = vector.get("record").and_then(Value::as_str);
        let others = vector.get("others");

        let index = |key: &str| -> Option<Record> {
            if key == host {
                return primary.map(|hex| Record {
                    bytes: hex_to_bytes(hex),
                });
            }
            others
                .and_then(Value::as_object)
                .and_then(|map| map.get(key))
                .and_then(Value::as_str)
                .map(|hex| Record {
                    bytes: hex_to_bytes(hex),
                })
        };

        let actual = match resolve_name(host, &index, has_head, now) {
            Outcome::Ok { source, value_hex } => {
                // The VALUE is compared where the vector names one, exactly as the
                // reference suite does: type alone once let two conforming readers
                // fetch different content from the same signed record.
                let names_value = vector
                    .get("expect")
                    .and_then(|e| e.get("value"))
                    .and_then(Value::as_str)
                    .is_some();
                if names_value {
                    format!("ok:{source}:{}", value_hex.unwrap_or_default())
                } else {
                    format!("ok:{source}")
                }
            }
            Outcome::Error(code) => format!("error:{code}"),
        };

        let want = match vector.get("expect") {
            Some(e) if e.get("outcome").and_then(Value::as_str) == Some("ok") => {
                let source = e.get("source").and_then(Value::as_str).unwrap_or("?");
                match e.get("value").and_then(Value::as_str) {
                    Some(value) => format!("ok:{source}:{value}"),
                    None => format!("ok:{source}"),
                }
            }
            Some(e) => format!(
                "error:{}",
                e.get("code").and_then(Value::as_str).unwrap_or("?")
            ),
            None => "?".to_string(),
        };
        if actual != want {
            failures.push(format!("{name}\n  want: {want}\n  got:  {actual}"));
        }
    }
    assert!(
        failures.is_empty(),
        "{} resolution vector(s) disagree:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn every_pow_vector_agrees_with_the_difficulty_schedule() {
    let raw = std::fs::read_to_string(VECTORS_PATH).expect("vectors.json exists");
    let doc: Value = serde_json::from_str(&raw).expect("vectors.json parses");
    let vectors = doc
        .get("pow")
        .and_then(Value::as_array)
        .expect("a pow section")
        .clone();

    let mut failures: Vec<String> = Vec::new();
    for vector in &vectors {
        let name = vector.get("name").and_then(Value::as_str).unwrap_or("?");
        let rule = vector.get("rule").and_then(Value::as_str).unwrap_or("");
        let check = vector
            .get("check")
            .and_then(Value::as_str)
            .unwrap_or("?")
            .to_string();
        let expect = vector.get("expect");

        // Each check names its own inputs. A miss is a FAILURE, not a skip: an
        // unknown check means the two suites have drifted apart structurally and
        // this consumer must grow the case, not ignore it.
        let agrees: bool = match check.as_str() {
            "baseBits" => {
                let len = vector
                    .get("labelLength")
                    .and_then(Value::as_u64)
                    .unwrap_or(0) as usize;
                vayuweb_client::pow::base_bits(len)
                    == expect.and_then(Value::as_u64).unwrap_or(u64::MAX) as u32
            }
            "requiredBits" => {
                let len = vector
                    .get("labelLength")
                    .and_then(Value::as_u64)
                    .unwrap_or(0) as usize;
                let window_count = vector
                    .get("windowCount")
                    .and_then(Value::as_u64)
                    .unwrap_or(0);
                vayuweb_client::pow::required_bits(len, window_count)
                    == expect.and_then(Value::as_u64).unwrap_or(u64::MAX) as u32
            }
            "rateWindow" => {
                let not_before = vector.get("notBefore").and_then(Value::as_u64).unwrap_or(0);
                let (start, end) = vayuweb_client::pow::rate_window(not_before);
                start
                    == expect
                        .and_then(|e| e.get("start"))
                        .and_then(Value::as_u64)
                        .unwrap_or(1)
                    && end
                        == expect
                            .and_then(|e| e.get("end"))
                            .and_then(Value::as_u64)
                            .unwrap_or(0)
            }
            "salt" => {
                // REGISTRY.md: salt = SHA-256("vayuweb-pow-v1" || record without sig
                // and without powProof.nonce)[0..16]. The reference authored the
                // record; both sides must derive the same 16 bytes from it.
                let hex = vector.get("record").and_then(Value::as_str).unwrap_or("");
                let want = expect.and_then(Value::as_str).unwrap_or("").to_lowercase();
                match vayuweb_client::record::decode_record(&hex_to_bytes(hex)) {
                    Ok(vayuweb_client::cbor::Value::Map(members)) => matches!(
                        vayuweb_client::pow::pow_salt(&members),
                        Ok(salt) if bytes_to_hex(&salt) == want
                    ),
                    _ => false,
                }
            }
            "tagSatisfies" => {
                let tag = hex_to_bytes(vector.get("tag").and_then(Value::as_str).unwrap_or(""));
                let bits = vector.get("bits").and_then(Value::as_u64).unwrap_or(0) as u32;
                vayuweb_client::pow::tag_satisfies(&tag, bits)
                    == expect.and_then(Value::as_bool).unwrap_or(!true)
            }
            other => {
                failures.push(format!(
                    "{name}: unknown check {other:?} — the suites have drifted; extend this consumer"
                ));
                continue;
            }
        };
        if !agrees {
            failures.push(format!("{name}\n  rule: {rule}\n  check: {check}"));
        }
    }
    assert!(
        failures.is_empty(),
        "{} pow vector(s) disagree:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn every_release_vector_names_the_same_return_to_the_pool() {
    let raw = std::fs::read_to_string(VECTORS_PATH).expect("vectors.json exists");
    let doc: Value = serde_json::from_str(&raw).expect("vectors.json parses");
    let vectors = doc
        .get("release")
        .and_then(Value::as_array)
        .expect("a release section")
        .clone();

    let mut failures: Vec<String> = Vec::new();
    for vector in &vectors {
        let name = vector.get("name").and_then(Value::as_str).unwrap_or("?");
        let at = vector.get("at").and_then(Value::as_u64).unwrap_or(0);
        let want = vector
            .get("expectFullyReleased")
            .and_then(Value::as_bool)
            .unwrap_or(false);
        let hex = vector
            .get("predecessor")
            .and_then(Value::as_str)
            .expect("a predecessor record");
        let bytes = hex_to_bytes(hex);
        let peeked = vayuweb_client::verify::peek(&bytes).expect("peeks");
        let tip = vayuweb_client::verify::PrevView {
            op_text: peeked.op,
            seq: peeked.seq,
            not_before: peeked.not_before,
            not_after: field_u64(&bytes, "notAfter").expect("notAfter"),
            owner_key: [0u8; 32],
            signer_key: [0u8; 32],
            suite: 1,
            hash: [0u8; 32],
            revoked: false,
        };
        let got = vayuweb_client::verify::fully_released(&tip, at);
        if got != want {
            failures.push(format!(
                "{name}\n  at {at}: want fullyReleased={want}, got {got}"
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} release vector(s) disagree:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn every_convergence_vector_picks_the_smaller_digest() {
    let raw = std::fs::read_to_string(VECTORS_PATH).expect("vectors.json exists");
    let doc: Value = serde_json::from_str(&raw).expect("vectors.json parses");
    let vectors = doc
        .get("convergence")
        .and_then(Value::as_array)
        .expect("a convergence section")
        .clone();

    let mut failures: Vec<String> = Vec::new();
    for vector in &vectors {
        let name = vector.get("name").and_then(Value::as_str).unwrap_or("?");
        // REGISTRY.md's convergence rule, decided on the record_hash of the EXACT
        // bytes each side holds: the smaller hash as a big-endian integer wins. This
        // is the same comparison the client's replay walk now applies at every fork
        // slot; these vectors pin the primitive both directions.
        let a_hex = vector.get("a").and_then(Value::as_str).unwrap_or("");
        let b_hex = vector.get("b").and_then(Value::as_str).unwrap_or("");
        let hash_a = vayuweb_client::domain::record_hash_from_bytes(&hex_to_bytes(a_hex));
        let hash_b = vayuweb_client::domain::record_hash_from_bytes(&hex_to_bytes(b_hex));
        let winner = if hash_a < hash_b { "a" } else { "b" };
        let want_winner = vector
            .get("expect")
            .and_then(|e| e.get("winner"))
            .and_then(Value::as_str)
            .unwrap_or("?");
        if winner != want_winner {
            failures.push(format!("{name}: want {want_winner}, got {winner}"));
        }
        let want_rule = vector
            .get("expect")
            .and_then(|e| e.get("rule"))
            .and_then(Value::as_str)
            .unwrap_or("?");
        if want_rule != "SMALLER_HASH" {
            failures.push(format!(
                "{name}: this consumer implements SMALLER_HASH only, vector says {want_rule:?}"
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} convergence vector(s) disagree:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn every_equivocation_vector_judges_the_evidence_alike() {
    let raw = std::fs::read_to_string(VECTORS_PATH).expect("vectors.json exists");
    let doc: Value = serde_json::from_str(&raw).expect("vectors.json parses");
    let vectors = doc
        .get("equivocation")
        .and_then(Value::as_array)
        .expect("an equivocation section")
        .clone();

    let mut failures: Vec<String> = Vec::new();
    for vector in &vectors {
        let name = vector.get("name").and_then(Value::as_str).unwrap_or("?");
        // REPLICATION.md 6.1 evidence, judged from the two encodings alone: same
        // name+tld+seq under the SAME owner key but different bytes, each half
        // attributable by its controlling signature. Validity conditions — expiry,
        // proof of work, chain position — are deliberately NOT part of the judgment.
        let a_hex = vector.get("a").and_then(Value::as_str).unwrap_or("");
        let b_hex = vector.get("b").and_then(Value::as_str).unwrap_or("");
        let got = vayuweb_client::verify::is_equivocation_evidence(
            &hex_to_bytes(a_hex),
            &hex_to_bytes(b_hex),
        );
        let want = vector
            .get("expect")
            .and_then(|e| e.get("equivocation"))
            .and_then(Value::as_bool)
            .unwrap_or(false);
        if got != want {
            failures.push(format!("{name}: want equivocation={want}, got {got}"));
        }
    }
    assert!(
        failures.is_empty(),
        "{} equivocation vector(s) disagree:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn every_block_exchange_vector_decodes_as_the_wire_contract_requires() {
    let raw = std::fs::read_to_string(VECTORS_PATH).expect("vectors.json exists");
    let doc: Value = serde_json::from_str(&raw).expect("vectors.json parses");
    let vectors = doc
        .get("blockExchange")
        .and_then(Value::as_array)
        .expect("a blockExchange section")
        .clone();

    let mut failures: Vec<String> = Vec::new();
    for vector in &vectors {
        let name = vector.get("name").and_then(Value::as_str).unwrap_or("?");
        // Some vectors carry fixed bytes; others CONSTRUCT a message at runtime
        // (an oversized block is a megabyte of zeros nobody wants to ship in JSON).
        // The construction mirrors the reference suite's exactly.
        let bytes = match vector.get("message").and_then(Value::as_str) {
            Some(hex) => hex_to_bytes(hex),
            None => {
                let construct = vector.get("construct").expect("message or construct");
                let count = construct.get("count").and_then(Value::as_u64).unwrap_or(0);
                let size = construct.get("bytes").and_then(Value::as_u64).unwrap_or(0);
                vayuweb_client::cbor::encode(&vayuweb_client::cbor::Value::Map(vec![
                    (
                        vayuweb_client::cbor::Key::Text("t".to_string()),
                        vayuweb_client::cbor::Value::Text("BLOCKS".to_string()),
                    ),
                    (
                        vayuweb_client::cbor::Key::Text("blks".to_string()),
                        vayuweb_client::cbor::Value::Array(
                            (0..count)
                                .map(|_| {
                                    vayuweb_client::cbor::Value::Bytes(vec![0u8; size as usize])
                                })
                                .collect(),
                        ),
                    ),
                ]))
                .expect("constructed message encodes")
            }
        };
        let expect = vector.get("expect");
        let want_decode = expect
            .and_then(|e| e.get("decode"))
            .and_then(Value::as_str)
            .unwrap_or("?")
            .to_string();
        let want_code = expect.and_then(|e| e.get("code")).and_then(Value::as_str);
        let result = vayuweb_client::blockx::decode_block_message(&bytes);
        match (want_decode.as_str(), want_code) {
            ("ok", _) => match result {
                Ok(message) => {
                    let kind = match message {
                        vayuweb_client::blockx::BlockMessage::BHello { .. } => "BHELLO",
                        vayuweb_client::blockx::BlockMessage::BWant { .. } => "BWANT",
                        vayuweb_client::blockx::BlockMessage::Blocks { .. } => "BLOCKS",
                        vayuweb_client::blockx::BlockMessage::BDone { .. } => "BDONE",
                    };
                    let want_type = expect
                        .and_then(|e| e.get("type"))
                        .and_then(Value::as_str)
                        .unwrap_or(kind);
                    if kind != want_type {
                        failures.push(format!(
                            "{name}: decoded as {kind}, vector names {want_type}"
                        ));
                    }
                }
                Err(e) => failures.push(format!("{name}: refused but should decode: {e}")),
            },
            ("reject", Some(want)) => match result {
                Ok(_) => failures.push(format!("{name}: decoded but should refuse {want}")),
                Err(e) => {
                    // The error Display carries the wire-contract code verbatim.
                    if !e.to_string().contains(want) {
                        failures.push(format!("{name}: refused as {e}, vector names {want}"));
                    }
                }
            },
            _ => failures.push(format!("{name}: unreadable expectation")),
        }
    }
    assert!(
        failures.is_empty(),
        "{} block-exchange vector(s) disagree:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn every_replication_vector_decodes_as_the_wire_contract_requires() {
    let raw = std::fs::read_to_string(VECTORS_PATH).expect("vectors.json exists");
    let doc: Value = serde_json::from_str(&raw).expect("vectors.json parses");
    let vectors = doc
        .get("replication")
        .and_then(Value::as_array)
        .expect("a replication section")
        .clone();

    let mut failures: Vec<String> = Vec::new();
    for vector in &vectors {
        let name = vector.get("name").and_then(Value::as_str).unwrap_or("?");
        let hex = vector.get("message").and_then(Value::as_str).unwrap_or("");
        let expect = vector.get("expect");
        let want_decode = expect
            .and_then(|e| e.get("decode"))
            .and_then(Value::as_str)
            .unwrap_or("?")
            .to_string();
        let want_code = expect.and_then(|e| e.get("code")).and_then(Value::as_str);
        let result = vayuweb_client::replicate::decode_message(&hex_to_bytes(hex));
        match (want_decode.as_str(), want_code) {
            ("ok", _) => match result {
                Ok(message) => {
                    let kind = match message {
                        vayuweb_client::replicate::ReplicationMessage::Hello { .. } => "HELLO",
                        vayuweb_client::replicate::ReplicationMessage::Want { .. } => "WANT",
                        vayuweb_client::replicate::ReplicationMessage::Records { .. } => "RECORDS",
                        vayuweb_client::replicate::ReplicationMessage::Checkpoint { .. } => {
                            "CHECKPOINT"
                        }
                        vayuweb_client::replicate::ReplicationMessage::Equivocation { .. } => {
                            "EQUIVOCATION"
                        }
                    };
                    let want_type = expect
                        .and_then(|e| e.get("type"))
                        .and_then(Value::as_str)
                        .unwrap_or(kind);
                    if kind != want_type {
                        failures.push(format!(
                            "{name}: decoded as {kind}, vector names {want_type}"
                        ));
                    }
                }
                Err(e) => failures.push(format!("{name}: refused but should decode: {e}")),
            },
            ("reject", Some(want)) => match result {
                Ok(_) => failures.push(format!("{name}: decoded but should refuse {want}")),
                Err(e) => {
                    if !e.to_string().contains(want) {
                        failures.push(format!("{name}: refused as {e}, vector names {want}"));
                    }
                }
            },
            _ => failures.push(format!("{name}: unreadable expectation")),
        }
    }
    assert!(
        failures.is_empty(),
        "{} replication vector(s) disagree:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
