/**
 * Regenerate conformance/vectors.json.
 *
 *     npm run vectors
 *
 * The artifact is committed, and a test compares it against a fresh generation. That is
 * deliberate: the vectors are the interoperability contract, so a change to any encoding rule
 * must show up as a reviewable diff in the file rather than as a silently different expectation.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  buildVectors,
  buildConvergenceVectors,
  buildResolutionVectors,
  buildReplicationVectors,
  buildEquivocationVectors,
  buildPowVectors,
  buildBlockExchangeVectors,
  VECTOR_NOW,
  VECTOR_OWNER_KEY,
  VECTOR_OTHER_KEY,
  toHex,
} from '../src/vectors.ts';

const OUT = fileURLToPath(new URL('../../conformance/vectors.json', import.meta.url));

const vectors = buildVectors();
const convergence = buildConvergenceVectors();
const resolution = buildResolutionVectors();
const replication = buildReplicationVectors();
const equivocation = buildEquivocationVectors();
const pow = buildPowVectors();
const blockExchange = buildBlockExchangeVectors();

const artifact = {
  $comment:
    'Conformance vectors for the VayuWeb registry. Generated by registry/scripts/' +
    'generate-vectors.ts — do not edit by hand. Each vector is a record in hex, the registry ' +
    'state to verify it against, the instant to verify it at, and the verdict every conforming ' +
    'implementation must return. The rejection CODE is part of the contract, not just the ' +
    'outcome: a record with two defects must produce the same code everywhere, which is what ' +
    'makes check order testable across implementations.',
  version: 1,
  generatedFor: 'docs/spec/REGISTRY.md',
  notes: {
    clock:
      'now is a Unix timestamp in seconds. Vectors never depend on the wall clock of the ' +
      'machine running them.',
    proofOfWork:
      'state.powVerified injects the result of proof-of-work verification rather than ' +
      'requiring a 64 MiB Argon2id evaluation per vector. The `pow` suite covers the ' +
      'derivations around the evaluation — difficulty from label length and rate, the rate ' +
      'window, salt derivation and the leading-zero-bit test — none of which need an Argon2id ' +
      'call. The evaluation itself is a standard primitive with its own published vectors; ' +
      'solved nonces at real difficulty live in the implementation test suite. Passing `pow` ' +
      'does not demonstrate a correct Argon2id.',
    keys:
      'Fixed test keys, derived from all-0x42 and all-0x77 seeds. Not secret. Never to be ' +
      'used for anything real.',
    ownerKey: toHex(VECTOR_OWNER_KEY),
    otherKey: toHex(VECTOR_OTHER_KEY),
    baseInstant: VECTOR_NOW,
    suites:
      'record pins what a verifier accepts. convergence, resolution, replication, ' +
      'equivocation and pow pin what implementations must AGREE about after that, which is ' +
      'where a fork lives — every consensus-critical defect found in this project so far was ' +
      'invisible to record verification and visible only to the question "what would a second ' +
      'implementation do". blockExchange is the wire format of VWIP-0005, which is a DRAFT: ' +
      'these vectors are generated so that the proposal carries executed encodings rather than ' +
      'transcribed ones, and they are not stable until it leaves Draft.',
  },
  vectors,
  convergence,
  resolution,
  replication,
  equivocation,
  pow,
  blockExchange,
};

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, `${JSON.stringify(artifact, null, 2)}\n`, 'utf8');
process.stdout.write(
  `wrote ${vectors.length} record, ${convergence.length} convergence, ${resolution.length} ` +
    `resolution, ${replication.length} replication, ${equivocation.length} equivocation and ` +
    `${pow.length} proof-of-work and ${blockExchange.length} block-exchange vectors to ${OUT}\n`,
);
