/**
 * Regenerate conformance/vectors.json.
 *
 *     npm run vectors
 *
 * The artifact is committed, and a test compares it against a fresh generation. That is
 * deliberate: the vectors are the interoperability contract, so a change to any encoding rule
 * must show up as a reviewable diff in the file rather than as a silently different expectation.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  buildVectors,
  buildConvergenceVectors,
  buildResolutionVectors,
  buildReplicationVectors,
  buildEquivocationVectors,
  buildPowVectors,
  buildBlockExchangeVectors,
  buildReleaseVectors,
  VECTOR_NOW,
  VECTOR_OWNER_KEY,
  VECTOR_OTHER_KEY,
  toHex,
} from '../src/vectors.ts';

const OUT = fileURLToPath(new URL('../../conformance/vectors.json', import.meta.url));

const vectors = buildVectors();
const convergence = buildConvergenceVectors();
const resolution = buildResolutionVectors();
const replication = buildReplicationVectors();
const equivocation = buildEquivocationVectors();
const pow = buildPowVectors();
const blockExchange = buildBlockExchangeVectors();
const release = buildReleaseVectors();

const artifact = {
  $comment:
    'Conformance vectors for the VayuWeb registry. Generated by registry/scripts/' +
    'generate-vectors.ts — do not edit by hand. Each vector is a record in hex, the registry ' +
    'state to verify it against, the instant to verify it at, and the verdict every conforming ' +
    'implementation must return. The rejection CODE is part of the contract, not just the ' +
    'outcome: a record with two defects must produce the same code everywhere, which is what ' +
    'makes check order testable across implementations.',
  version: 1,
  // Every document a suite here comes from. It named REGISTRY.md alone while the file carried
  // vectors for six other specifications — true when written, and steadily less true afterwards.
  // A runner outside this repository uses this to know which text to read beside which suite.
  generatedFor: [
    'docs/spec/REGISTRY.md',
    'docs/spec/RESOLUTION.md',
    'docs/spec/REPLICATION.md',
    'docs/spec/PROOF-OF-WORK.md',
    'docs/spec/VWIP-0005.md',
  ],
  notes: {
    clock:
      'now is a Unix timestamp in seconds. Vectors never depend on the wall clock of the ' +
      'machine running them.',
    proofOfWork:
      'state.powVerified injects the result of proof-of-work verification rather than ' +
      'requiring a 64 MiB Argon2id evaluation per vector. The `pow` suite covers the ' +
      'derivations around the evaluation — difficulty from label length and rate, the rate ' +
      'window, salt derivation and the leading-zero-bit test — none of which need an Argon2id ' +
      'call. The evaluation itself is a standard primitive with its own published vectors; ' +
      'solved nonces at real difficulty live in the implementation test suite. Passing `pow` ' +
      'does not demonstrate a correct Argon2id.',
    keys:
      'Fixed test keys, derived from all-0x42 and all-0x77 seeds. Not secret. Never to be ' +
      'used for anything real.',
    ownerKey: toHex(VECTOR_OWNER_KEY),
    otherKey: toHex(VECTOR_OTHER_KEY),
    baseInstant: VECTOR_NOW,
    release:
      'A `release` vector is a predecessor record in hex and an instant, and the answer every ' +
      'implementation must derive: is the name claimable again by anyone. It is the one thing ' +
      'the record suite could not test, because `state.fullyReleased` is an INPUT there — every ' +
      'other vector in this file is handed the answer and checked on what it does with it. Two ' +
      'implementations deriving it differently accept different owners for the same name, and ' +
      'neither ever rejects anything. REVOKE is why it is published rather than assumed: an ' +
      'ordinary record is released at notAfter + 2592000 + 2592000, a revoked one at ' +
      'notAfter + 2592000, because grace would be a window in which a compromised key could ' +
      'renew. Applying the ordinary rule to both holds a revoked name for thirty days longer ' +
      'than peers who do not. Read the `predecessor` bytes, compute the answer at `at`, compare ' +
      'with `expectFullyReleased`; no internal state label is published, because the name being ' +
      'available is the only part of this that peers see.',
    suites:
      'The suites, by their key in this file. `vectors` pins what a verifier accepts. ' +
      '`convergence`, `resolution`, `replication`, `equivocation`, `pow` and `release` pin ' +
      'what implementations must AGREE about after that, which is ' +
      'where a fork lives — every consensus-critical defect found in this project so far was ' +
      'invisible to record verification and visible only to the question "what would a second ' +
      'implementation do". blockExchange is the wire format of VWIP-0005, which is a DRAFT: ' +
      'these vectors are generated so that the proposal carries executed encodings rather than ' +
      'transcribed ones, and they are not stable until it leaves Draft.',
    construct:
      'A vector carries EITHER a `message` in hex OR a `construct` recipe, never neither. A ' +
      'recipe is used where publishing the bytes would publish no information: the one case ' +
      'today is a block one octet over the megabyte limit, which written out is 2.1 MB of hex ' +
      'zeros of which every byte after the first says nothing. Build the message from the recipe ' +
      'and decode it exactly as you would a hex one. Kinds: `blocks-of-zeros` — a BLOCKS message ' +
      'whose `blks` array holds `count` byte strings of `bytes` zero octets each, encoded as ' +
      'deterministic CBOR per REGISTRY.md. This list is closed; a runner meeting a kind it does ' +
      'not know must fail rather than skip, because a skipped vector reports as a passing one.',
  },
  vectors,
  convergence,
  resolution,
  replication,
  equivocation,
  pow,
  blockExchange,
  release,
};

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, `${JSON.stringify(artifact, null, 2)}\n`, 'utf8');
process.stdout.write(
  `wrote ${vectors.length} record, ${convergence.length} convergence, ${resolution.length} ` +
    `resolution, ${replication.length} replication, ${equivocation.length} equivocation, ` +
    `${pow.length} proof-of-work, ${blockExchange.length} block-exchange and ${release.length} ` +
    `release vectors to ${OUT}\n`,
);
