#!/usr/bin/env python3
"""Generate site/assets/namespace.js from docs/spec/NAMESPACE-CATALOGUE.md.

The landing page lets a reader search the namespace. That namespace is normative
— Constitution Article 35.1 incorporates the Annex by reference, the enumeration
is closed, and Article 2.31 requires a Node to decide validity from the copy it
holds. A site that showed a hand-maintained subset would be publishing a second,
divergent namespace with the authority of the project's own front page.

So the page reads from the Annex, through this. The Annex is the source; the
generated file carries a count and a digest of what it was generated from, and
--check fails if the two have parted company.

    python3 site/tools/embed-namespace.py [--check]
"""
import hashlib
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SOURCE = os.path.join(ROOT, "docs", "spec", "NAMESPACE-CATALOGUE.md")
TARGET = os.path.join(ROOT, "site", "assets", "namespace.js")

# A category section is a `## Heading` followed by an `*N extensions*` count. The
# count line is what separates a category from the Annex's prose sections, and it
# is also the Annex's own assertion about itself — so it is checked rather than
# trusted, below.
SECTION = re.compile(r"^## (.+)$", re.M)
DECLARED = re.compile(r"^\*(\d+) extensions\*", re.M)
ROW = re.compile(r"^\| `(\.[a-z0-9]{2,12})` \| ([^|]+?) \|", re.M)


def parse(text):
    categories, problems = [], []
    parts = SECTION.split(text)
    for index in range(1, len(parts), 2):
        name, body = parts[index].strip(), parts[index + 1]
        declared = DECLARED.search(body)
        if declared is None:
            continue
        rows = ROW.findall(body)
        if not rows:
            continue
        if int(declared.group(1)) != len(rows):
            problems.append(
                f"{name}: the Annex says {declared.group(1)} extensions and the table has {len(rows)}"
            )
        # Extensions only, not the Annex's "who registers it" column.
        #
        # This is a size decision and it is worth stating rather than hiding. The
        # descriptions are 66 kB — five times the extensions themselves — inside a
        # bundle that has to be small enough to publish in one piece. What the
        # page must not compromise on is COMPLETENESS: the namespace is a closed,
        # enumerated set that Article 2.31 requires a Node to decide offline from
        # its own copy, so a front page carrying 300 of 1,270 would be publishing
        # a second, divergent namespace with the project's authority. All 1,270
        # ship; each is shown with its category, and the Annex is linked for what
        # each one is for.
        # One space-joined string per category rather than an array of quoted
        # strings. Same information, a third fewer bytes, and — the reason it is
        # worth doing — the shape is legible: a person or a diff can see that a
        # category still holds the words it held, where 40 quoted-and-comma'd
        # items are a wall nobody proofreads. The leading dot is added back on
        # the page; carrying it 1,270 times is 1,270 wasted bytes.
        categories.append({"name": name, "entries": " ".join(tld[1:] for tld, _ in rows)})
    return categories, problems


def render():
    with open(SOURCE, encoding="utf-8") as handle:
        text = handle.read()
    categories, problems = parse(text)
    if problems:
        return None, problems
    # Count the words, not the characters. `entries` became a joined string and
    # this line went on returning a number — 9,263, the character count — which
    # the page's own integrity check caught on the next load. A count derived
    # from the same representation the page parses cannot drift from it again.
    total = sum(len(c["entries"].split(" ")) for c in categories)
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]
    payload = json.dumps(
        {"total": total, "source": digest, "categories": categories},
        separators=(",", ":"),
        ensure_ascii=False,
    )
    body = (
        "/* Generated by site/tools/embed-namespace.py — do not edit.\n"
        "   Source: docs/spec/NAMESPACE-CATALOGUE.md, the normative Annex incorporated\n"
        f"   by Constitution Article 35.1. {total} extensions; source sha256 {digest}… */\n"
        f"window.VAYUWEB_NAMESPACE = {payload};\n"
    )
    return body, []


def main():
    want, problems = render()
    if problems:
        for problem in problems:
            print(f"FAIL — {problem}")
        return 1
    if "--check" in sys.argv:
        try:
            with open(TARGET, encoding="utf-8") as handle:
                have = handle.read()
        except OSError:
            print(f"FAIL — {TARGET} does not exist; run site/tools/embed-namespace.py")
            return 1
        if have != want:
            print(f"FAIL — {TARGET} no longer matches the Annex; run site/tools/embed-namespace.py")
            return 1
        print("OK — the site's namespace matches the Annex.")
        return 0
    os.makedirs(os.path.dirname(TARGET), exist_ok=True)
    with open(TARGET, "w", encoding="utf-8") as handle:
        handle.write(want)
    print(f"wrote {TARGET} ({len(want)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
