#!/usr/bin/env python3
"""Point the site at the repository's own brand artwork, unmodified.

The mark is served by the install's media library, and its stored name is the
first 32 hex characters of the file's SHA-256 — the library is content-addressed
and collapses duplicate uploads onto the same URL. So the URL is not a magic
string to be pasted and kept in step by hand: it is DERIVED here from
`assets/vayuweb-mark-dark-256.png`, and changing the artwork changes the URL in
the same commit that changes the bytes.

Two destinations, because they have different jobs:

  * `site/assets/brand.css` — a `--vw-mark` variable, used for every painted
    instance (header, footer, hero watermark, closing panel).
  * the `<link rel="icon">` in `site/index.html` — a favicon has to be a URL in
    the markup, so it cannot come from a stylesheet. A bundle that ships no
    favicon does not inherit one: the install answers 404 rather than lend the
    primary domain's logo to somebody else's site, so the tab would be blank.

WHY A URL RATHER THAN AN INLINE `data:` URI, which the policy also admits. The
bundle is published by handing the entire file set to the install in one call,
so 24 kB of base64 is a cost paid against the thing that decides whether the
site can be published at all. `/media` is same-origin — it is not scoped per
host — so `img-src 'self'` admits it with nothing widened, the browser caches it
apart from the stylesheet, and the render-blocking CSS drops to a few hundred
bytes.

The one thing this cannot check offline is that the file is still IN the library.
If it is ever removed, re-uploading the same bytes restores the same URL, because
the name is the hash of the bytes.

    python3 site/tools/embed-mark.py [--check]

--check exits non-zero if either destination is stale.
"""
import hashlib
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SOURCE = os.path.join(ROOT, "assets", "vayuweb-mark-dark-256.png")
TARGET = os.path.join(ROOT, "site", "assets", "brand.css")
INDEX = os.path.join(ROOT, "site", "index.html")

BANNER = """/* Generated by site/tools/embed-mark.py — do not edit.
   assets/vayuweb-mark-dark-256.png, served by the install's content-addressed
   media library. The name is the first 32 hex of the file's SHA-256. */
"""

ICON_TAG = re.compile(r'<link rel="icon" href="[^"]*"[^>]*>')


def media_url():
    with open(SOURCE, "rb") as handle:
        digest = hashlib.sha256(handle.read()).hexdigest()[:32]
    return f"/media/{digest}.png"


def render_css(url):
    return f"{BANNER}:root {{\n  --vw-mark: url({url});\n}}\n"


def render_index(url):
    with open(INDEX, encoding="utf-8") as handle:
        text = handle.read()
    if not ICON_TAG.search(text):
        return None, 'site/index.html has no <link rel="icon" …> to fill'
    tag = f'<link rel="icon" href="{url}" type="image/png">'
    return ICON_TAG.sub(lambda _: tag, text, count=1), None


def main():
    url = media_url()
    css = render_css(url)
    index, error = render_index(url)
    if error is not None:
        print(f"FAIL — {error}")
        return 1

    if "--check" in sys.argv:
        failed = False
        for path, want in ((TARGET, css), (INDEX, index)):
            rel = os.path.relpath(path, ROOT)
            try:
                with open(path, encoding="utf-8") as handle:
                    have = handle.read()
            except OSError:
                print(f"FAIL — {rel} does not exist; run site/tools/embed-mark.py")
                failed = True
                continue
            if have != want:
                print(f"FAIL — {rel} does not point at the current mark; run site/tools/embed-mark.py")
                failed = True
        if failed:
            return 1
        print(f"OK — the site points at the current brand mark ({url}).")
        return 0

    os.makedirs(os.path.dirname(TARGET), exist_ok=True)
    with open(TARGET, "w", encoding="utf-8") as handle:
        handle.write(css)
    with open(INDEX, "w", encoding="utf-8") as handle:
        handle.write(index)
    print(f"wrote {os.path.relpath(TARGET, ROOT)} and the favicon in "
          f"{os.path.relpath(INDEX, ROOT)} → {url}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
