#!/usr/bin/env python3
"""Generate site/assets/claims.js from Article 21.4 of the Constitution.

The landing page shows the reader which claims this project forbids itself from
making. Printing that list is worth doing — it is the most credible thing on the
page — but it means the marketing copy contains, word for word, every phrase the
charter prohibits.

`scripts/check-absolute-claims.py` now reads the site as well as the corpus, and
it would be right to fail on those words: the test in Article 21.5 is what a
sentence asserts to a reader who has read nothing else. The charter has the same
problem and solves it with an exemption, "it must be able to quote what it
forbids". Copying that exemption onto `site/index.html` would be the wrong shape
— it would exempt the ENTIRE marketing page, which is the one surface most
likely to make a forbidden claim by accident.

So the quotation is moved out of the page and into one generated file, which
carries the exemption alone. The page holds an empty list and fills it at
runtime. Three things follow, and all three are the point:

  * `site/index.html` stays fully covered by the gate.
  * The list is read out of Article 21.4 rather than restated, so amending the
    Article updates the site in the same commit — the same relationship the
    checker itself already has with the charter.
  * --check fails when the two have parted company.

    python3 site/tools/embed-claims.py [--check]
"""
import os
import json
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SOURCE = os.path.join(ROOT, "constitution", "CONSTITUTION.md")
TARGET = os.path.join(ROOT, "site", "assets", "claims.js")


def claims():
    with open(SOURCE, encoding="utf-8") as handle:
        text = handle.read()
    block = re.search(r"^21\.4 .*?^21\.5 ", text, re.S | re.M)
    if block is None:
        return None, "Article 21.4 is no longer where this expects it"
    # The quoted claims, then 21.4.i, which is a sentence rather than a quotation
    # and is the most important entry on the list — it is the one that catches a
    # phrasing nobody has written yet.
    quoted = re.findall(r'^21\.4\.[a-z] "([^"]+)";', block.group(0), re.M)
    if len(quoted) < 5:
        return None, f"Article 21.4 yielded only {len(quoted)} quoted claims; the format changed"
    catch_all = re.search(r"^21\.4\.[a-z] (any unqualified absolute[^\n]*?)\.?$", block.group(0), re.M)
    if catch_all is None:
        return None, "Article 21.4's catch-all clause is no longer recognisable"
    return quoted + [catch_all.group(1)], None


def render():
    items, error = claims()
    if error is not None:
        return None, error
    body = (
        "/* Generated by site/tools/embed-claims.py — do not edit.\n"
        "   Read out of Article 21.4 of the Constitution, which is the list of claims\n"
        "   this project forbids itself from making. Kept in its own file so that\n"
        "   site/index.html carries none of these words and stays covered by\n"
        "   scripts/check-absolute-claims.py. */\n"
        f"window.VAYUWEB_FORBIDDEN_CLAIMS = {json.dumps(items, ensure_ascii=False)};\n"
    )
    return body, None


def main():
    want, error = render()
    if error is not None:
        print(f"FAIL — {error}")
        return 1
    if "--check" in sys.argv:
        try:
            with open(TARGET, encoding="utf-8") as handle:
                have = handle.read()
        except OSError:
            print(f"FAIL — {TARGET} does not exist; run site/tools/embed-claims.py")
            return 1
        if have != want:
            print("FAIL — site/assets/claims.js no longer matches Article 21.4; "
                  "run site/tools/embed-claims.py")
            return 1
        print("OK — the site's forbidden-claims list matches Article 21.4.")
        return 0
    os.makedirs(os.path.dirname(TARGET), exist_ok=True)
    with open(TARGET, "w", encoding="utf-8") as handle:
        handle.write(want)
    print(f"wrote {os.path.relpath(TARGET, ROOT)} ({len(want)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
