#!/usr/bin/env python3
"""Build the VayuWeb brand asset set from the original artwork.

The source files are black-line artwork on a white canvas. This turns them into trimmed,
transparent PNGs in two ink colours -- near-black for light backgrounds, near-white for dark
ones -- at the sizes the repository and the website actually use.

    python3 scripts/build-assets.py assets/

Requires Pillow and numpy. Every file in assets/ except the two *-source.* originals is
generated by this script and should never be edited by hand.
"""
import os
import sys

import numpy as np
from PIL import Image, ImageFilter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets")
OUT = sys.argv[1] if len(sys.argv) > 1 else SRC
os.makedirs(OUT, exist_ok=True)

WHITE_POINT = 248.0   # luminance at/above which a pixel is fully transparent
BLACK_POINT = 40.0    # luminance at/below which a pixel is fully opaque

INK_LIGHT = (17, 17, 19)        # near-black, for light backgrounds
INK_DARK = (245, 247, 250)      # near-white, for dark backgrounds


def load_flat(path):
    """Load an image, flattening any alpha onto white, return float luminance."""
    im = Image.open(path)
    if im.mode in ("RGBA", "LA", "P"):
        im = im.convert("RGBA")
        bg = Image.new("RGBA", im.size, (255, 255, 255, 255))
        im = Image.alpha_composite(bg, im)
    return np.asarray(im.convert("L")).astype(np.float32)


def alpha_from(lum):
    a = (WHITE_POINT - lum) * (255.0 / (WHITE_POINT - BLACK_POINT))
    return np.clip(a, 0, 255).astype(np.uint8)


def rgba(alpha, ink):
    h, w = alpha.shape
    arr = np.zeros((h, w, 4), dtype=np.uint8)
    arr[..., 0] = ink[0]
    arr[..., 1] = ink[1]
    arr[..., 2] = ink[2]
    arr[..., 3] = alpha
    return Image.fromarray(arr, "RGBA")


def trim(alpha, pad_ratio=0.04, square=False):
    """Bounding box of visible ink with proportional padding."""
    ys, xs = np.nonzero(alpha > 8)
    y0, y1, x0, x1 = ys.min(), ys.max(), xs.min(), xs.max()
    span = max(y1 - y0, x1 - x0)
    pad = int(round(span * pad_ratio))
    if square:
        cy, cx = (y0 + y1) / 2.0, (x0 + x1) / 2.0
        half = span / 2.0 + pad
        y0, y1 = int(cy - half), int(cy + half)
        x0, x1 = int(cx - half), int(cx + half)
    else:
        y0, y1, x0, x1 = y0 - pad, y1 + pad, x0 - pad, x1 + pad
    return (int(x0), int(y0), int(x1) + 1, int(y1) + 1)


def shrink(img, w, h):
    """Resize, thickening hairlines first when the target is small.

    The artwork is drawn with very fine strokes; below roughly 64px a plain
    LANCZOS downscale averages them into near-invisible grey. Dilating the
    alpha at 4x the target before the final resize keeps the silhouette
    readable at favicon size without distorting it at normal sizes.
    """
    if w > 96:
        return img.resize((w, h), Image.LANCZOS)
    ss, k = (6, 9) if w <= 48 else (4, 5)
    big = img.resize((w * ss, h * ss), Image.LANCZOS)
    r, g, b, a = big.split()
    a = a.filter(ImageFilter.MaxFilter(k))
    return Image.merge("RGBA", (r, g, b, a)).resize((w, h), Image.LANCZOS)


def emit(alpha, name, widths, square=False, pad_ratio=0.04):
    """Write light and dark variants at the requested widths.

    Widths are clamped to the artwork's native size — the source is raster, so
    upscaling would only ship a blurrier file at a bigger number.
    """
    box = trim(alpha, pad_ratio=pad_ratio, square=square)
    native = box[2] - box[0]
    scales = []
    for w in widths:
        w = min(w, native)
        if w not in scales:
            scales.append(w)
    for ink, suffix in ((INK_LIGHT, ""), (INK_DARK, "-dark")):
        img = rgba(alpha, ink).crop(box)
        for w in scales:
            h = max(1, int(round(img.height * (w / img.width))))
            out = shrink(img, w, h)
            tag = "" if w == scales[0] else f"-{w}"
            path = os.path.join(OUT, f"{name}{suffix}{tag}.png")
            out.save(path, optimize=True)
            print(f"{os.path.basename(path):32s} {out.width}x{out.height}")


# ── primary artwork (1254px): spider mark above the VayuWeb wordmark ──────────
lum = load_flat(os.path.join(SRC, "vayuweb-logo-source.jpg"))
alpha = alpha_from(lum)

MARK_END = 795       # midpoint of the blank band between mark and wordmark
emit(alpha, "vayuweb-logo", [1024, 512, 256])
emit(alpha[:MARK_END], "vayuweb-mark", [1024, 512, 256, 180, 32], square=True, pad_ratio=0.06)
emit(alpha[MARK_END:], "vayuweb-wordmark", [1024, 512, 256])

# ── alternate artwork (500px): finer line weight, integrated wordmark ──────
lum2 = load_flat(os.path.join(SRC, "vayuweb-logo-alt-source.png"))
alpha2 = alpha_from(lum2)
emit(alpha2, "vayuweb-logo-alt", [500, 256])

# ── favicons: the mark centred on a square, both themes ────────────────────
box = trim(alpha[:MARK_END], pad_ratio=0.10, square=True)
for ink, suffix in ((INK_LIGHT, ""), (INK_DARK, "-dark")):
    src = rgba(alpha[:MARK_END], ink).crop(box)
    for size in (512, 180, 32):
        if size > src.width:
            continue
        icon = shrink(src, size, size)
        path = os.path.join(OUT, f"vayuweb-favicon-{size}{suffix}.png")
        icon.save(path, optimize=True)
        print(f"{os.path.basename(path):32s} {size}x{size}")
